#pragma once

#include <atomic>
#include <functional>
#include <memory>
#include <mutex>
#include <string>

#include "context/config.h"
#include "controller/config.h"
#include "controller/types.h"
#include "io/tool_registry.h"
#include "llm/config.h"
#include "policy/config.h"
#include "session/session.h"

namespace shizuru::runtime {

// Configuration bundle for creating an AgentRuntime.
struct RuntimeConfig {
  core::ControllerConfig controller;
  core::ContextConfig context;
  core::PolicyConfig policy;
  services::OpenAiConfig llm;

  // If true, when the latest user input is audio, AgentRuntime will try to
  // synthesize assistant text replies into audio via a registered TTS tool.
  bool auto_tts_on_audio_input = true;
};

// Final output emitted by AgentRuntime for a user turn.
struct RuntimeOutput {
  std::string text;

  // Serialized audio payload generated by a TTS tool (format is tool-defined).
  std::string audio_payload;
  std::string audio_mime_type = "audio/pcm";
  bool has_audio = false;
};

// Top-level entry point that assembles all components and manages
// the lifecycle of an AgentSession.
class AgentRuntime {
 public:
  using OutputCallback = std::function<void(const RuntimeOutput& output)>;

  AgentRuntime(RuntimeConfig config, services::ToolRegistry& tools);
  ~AgentRuntime();

  AgentRuntime(const AgentRuntime&) = delete;
  AgentRuntime& operator=(const AgentRuntime&) = delete;

  // Create and start a new session. Returns the session ID.
  std::string StartSession();

  // Send a user message to the active session.
  void SendMessage(const std::string& content);

  // Send user input with MIME type. For audio MIME types, runtime will try to
  // call STT tool first, then forward transcript to the agent.
  void SendInput(const std::string& payload,
                 const std::string& mime_type = "text/plain");

  // Register callback for final outputs (text and optional audio payload).
  void OnOutput(OutputCallback cb);

  // Shut down the active session.
  void Shutdown();

  // Query the current state of the active session.
  core::State GetState() const;

  // Check if a session is active.
  bool HasActiveSession() const;

 private:
  void EnqueueUserText(const std::string& content);
  void HandleAssistantResponse(const core::ActionCandidate& response);

  // Returns transcript on success; empty string when STT tool is unavailable
  // or transcription fails.
  std::string TranscribeAudioToText(const std::string& payload,
                                    const std::string& mime_type);

  // Phase B: optional VAD gate before STT.
  // Returns true when speech is detected or when no VAD tool is registered.
  bool PassesVadGate(const std::string& payload,
                     const std::string& mime_type);

  RuntimeOutput MaybeSynthesizeAudio(const RuntimeOutput& text_output,
                                     const core::ActionCandidate& response);

  bool ShouldSynthesizeAudio(const core::ActionCandidate& response) const;

  RuntimeConfig config_;
  services::ToolRegistry& tools_;
  std::unique_ptr<core::AgentSession> session_;

  std::atomic<bool> last_input_was_audio_{false};

  mutable std::mutex output_cb_mutex_;
  OutputCallback output_cb_;
};

}  // namespace shizuru::runtime
